title: Chuan Ran's Homepage
page-top-title: Chuan Ran
top-section-bg-text: Big Data Statistics
backgrounds:
  - static/assets/background/background_0.jpg
background-interval-ms: 7000
background-overlay: 0.52
copyright-text: '&copy; Chuan Ran 2024-2027. All Rights Reserved.'
github-link:
  text: Github
  href: https://github.com/ChuanRan515
license-link:
  text: License
  href: https://github.com/ChuanRan515/ChuanRan515.github.io/blob/main/LICENSE
sections:
  - id: home
    nav: HOME
    title: Chuan Ran &ensp;|&ensp;冉川
    href: '#page-top' # Default to '#<id>' if not specified
  - id: publications
    nav: PUBLICATIONS
    title: PUBLICATIONS
    icon: bi-file-text-fill
  - id: awards
    nav: AWARDS
    title: AWARDS
    icon: bi-award-fill
